import type {
  PrepositionBlankPart,
  PrepositionCategory,
  PrepositionStory,
} from '@shared/types'

export const prepositionStories: PrepositionStory[] = [
  {
    id: 'umzug-mit-system',
    title: 'Ein Umzug mit System',
    level: 'B1',
    kind: 'narrative',
    description: 'Eine ruhige Alltagsszene mit Richtungs- und Ortswechseln, ergänzt durch feste Verbindungen.',
    focus: ['location', 'verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Mira zieht am Samstag ' },
          { type: 'blank', id: 'umzug-1', category: 'location', answer: 'in die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' neue Wohnung. Schon früh stellt sie die Kartons ' },
          { type: 'blank', id: 'umzug-2', category: 'location', answer: 'neben die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Tür und hängt den Kalender ' },
          { type: 'blank', id: 'umzug-3', category: 'location', answer: 'an die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Wand. Ihr Bruder wartet ' },
          { type: 'blank', id: 'umzug-4', category: 'verb', answer: 'auf den', hint: 'warten auf + Akkusativ' },
          { type: 'text', content: ' Aufzug, während Mira sich ' },
          { type: 'blank', id: 'umzug-5', category: 'verb', answer: 'über die', hint: 'sich freuen über + Akkusativ', explanation: 'sich freuen über = jetzt froh sein; sich freuen auf = etwas Zukünftiges erwarten.' },
          { type: 'text', content: ' helle Küche freut.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Nach zwei Stunden steht der Schreibtisch ' },
          { type: 'blank', id: 'umzug-6', category: 'location', answer: 'vor dem', hint: 'wo? + Dativ', acceptedAnswers: ['vorm'] },
          { type: 'text', content: ' Fenster, die Lampe liegt noch ' },
          { type: 'blank', id: 'umzug-7', category: 'location', answer: 'unter dem', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Sofa. Beim Auspacken spricht Mira ' },
          { type: 'blank', id: 'umzug-8', category: 'verb', answer: 'mit dem', hint: 'sprechen mit + Dativ' },
          { type: 'text', content: ' Vermieter über den Keller. Am Abend hat sie endlich Vertrauen ' },
          { type: 'blank', id: 'umzug-9', category: 'noun', answer: 'in die', hint: 'Vertrauen in + Akkusativ' },
          { type: 'text', content: ' neue Ordnung und große Lust ' },
          { type: 'blank', id: 'umzug-10', category: 'noun', answer: 'auf den', hint: 'Lust auf + Akkusativ' },
          { type: 'text', content: ' ersten Kaffee am eigenen Tisch.' },
        ],
      },
    ],
  },
  {
    id: 'bahnhof-im-nebel',
    title: 'Orientierung am Bahnhof',
    level: 'A2-B1',
    kind: 'narrative',
    description: 'Eine Reiseepisode mit Wechselpräpositionen, Warte-Situationen und typischen Nomenverbindungen.',
    focus: ['location', 'verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Jonas kommt zu spät ' },
          { type: 'blank', id: 'bahnhof-1', category: 'location', answer: 'an den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Bahnhof. Sein Zug steht schon ' },
          { type: 'blank', id: 'bahnhof-2', category: 'location', answer: 'auf dem', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Gleis 7. Er denkt ' },
          { type: 'blank', id: 'bahnhof-3', category: 'verb', answer: 'an die', hint: 'denken an + Akkusativ', explanation: 'denken an = sich erinnern; denken über = eine Meinung bilden.' },
          { type: 'text', content: ' Fahrkarte, die noch ' },
          { type: 'blank', id: 'bahnhof-4', category: 'location', answer: 'in der', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Jackentasche steckt. Eine Durchsage warnt ' },
          { type: 'blank', id: 'bahnhof-5', category: 'verb', answer: 'vor dem', hint: 'warnen vor + Dativ' },
          { type: 'text', content: ' Ausfall eines Regionalzugs.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Auf dem Bahnsteig bittet er eine Mitarbeiterin ' },
          { type: 'blank', id: 'bahnhof-6', category: 'verb', answer: 'um eine', hint: 'bitten um + Akkusativ' },
          { type: 'text', content: ' Auskunft. Seine Sorge ' },
          { type: 'blank', id: 'bahnhof-7', category: 'noun', answer: 'um den', hint: 'Sorge um + Akkusativ' },
          { type: 'text', content: ' Anschluss ist berechtigt, denn der Bus fährt gleich ' },
          { type: 'blank', id: 'bahnhof-8', category: 'location', answer: 'vor dem', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Haupteingang ab. Schließlich steigt Jonas ' },
          { type: 'blank', id: 'bahnhof-9', category: 'location', answer: 'in den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Zug und hat trotz allem Hoffnung ' },
          { type: 'blank', id: 'bahnhof-10', category: 'noun', answer: 'auf eine', hint: 'Hoffnung auf + Akkusativ' },
          { type: 'text', content: ' pünktliche Ankunft.' },
        ],
      },
    ],
  },
  {
    id: 'sprechstunde',
    title: 'In der Sprechstunde',
    level: 'B1',
    kind: 'narrative',
    description: 'Ein Arzttermin mit körperlichen Beschwerden, Raumangaben und Beratungsverben.',
    focus: ['verb', 'location', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Lea wartet ' },
          { type: 'blank', id: 'arzt-1', category: 'verb', answer: 'auf den', hint: 'warten auf + Akkusativ' },
          { type: 'text', content: ' Arzt und setzt sich ' },
          { type: 'blank', id: 'arzt-2', category: 'location', answer: 'neben die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' ältere Dame. Ihre Angst ' },
          { type: 'blank', id: 'arzt-3', category: 'noun', answer: 'vor der', hint: 'Angst vor + Dativ' },
          { type: 'text', content: ' Untersuchung wird kleiner, als die Ärztin ruhig ' },
          { type: 'blank', id: 'arzt-4', category: 'verb', answer: 'mit ihr', hint: 'sprechen mit + Dativ' },
          { type: 'text', content: ' spricht. Das Rezept liegt bereits ' },
          { type: 'blank', id: 'arzt-5', category: 'location', answer: 'auf dem', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Schreibtisch.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Die Ärztin fragt Lea ' },
          { type: 'blank', id: 'arzt-6', category: 'verb', answer: 'nach den', hint: 'fragen nach + Dativ' },
          { type: 'text', content: ' Symptomen und rät ihr ' },
          { type: 'blank', id: 'arzt-7', category: 'verb', answer: 'zu einer', hint: 'raten zu + Dativ' },
          { type: 'text', content: ' Pause. Lea hat Vertrauen ' },
          { type: 'blank', id: 'arzt-8', category: 'noun', answer: 'zu der', hint: 'Vertrauen zu + Dativ', acceptedAnswers: ['zur'], explanation: 'Vertrauen zu betont die Person; Vertrauen in betont eher Fähigkeit oder System.' },
          { type: 'text', content: ' Ärztin. Zu Hause legt sie die Medikamente ' },
          { type: 'blank', id: 'arzt-9', category: 'location', answer: 'in den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Küchenschrank und achtet in den nächsten Tagen ' },
          { type: 'blank', id: 'arzt-10', category: 'verb', answer: 'auf ihre', hint: 'achten auf + Akkusativ' },
          { type: 'text', content: ' Gesundheit.' },
        ],
      },
    ],
  },
  {
    id: 'seminar-kunstliche-intelligenz',
    title: 'Ein Seminar über künstliche Intelligenz',
    level: 'B2',
    kind: 'expository',
    description: 'Ein sachlicher Text über ein Universitätsseminar, Diskussion und Vorbereitung.',
    focus: ['verb', 'noun', 'location'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Im Seminar beschäftigen sich die Studierenden ' },
          { type: 'blank', id: 'seminar-1', category: 'verb', answer: 'mit den', hint: 'sich beschäftigen mit + Dativ' },
          { type: 'text', content: ' Folgen künstlicher Intelligenz. Die Dozentin legt ein Diagramm ' },
          { type: 'blank', id: 'seminar-2', category: 'location', answer: 'auf den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Tisch und verweist ' },
          { type: 'blank', id: 'seminar-3', category: 'verb', answer: 'auf die', hint: 'verweisen auf + Akkusativ' },
          { type: 'text', content: ' aktuellen Zahlen. Viele haben Interesse ' },
          { type: 'blank', id: 'seminar-4', category: 'noun', answer: 'an der', hint: 'Interesse an + Dativ' },
          { type: 'text', content: ' Frage, ob Software gerechter entscheiden kann als Menschen.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Eine Gruppe bereitet sich ' },
          { type: 'blank', id: 'seminar-5', category: 'verb', answer: 'auf die', hint: 'sich vorbereiten auf + Akkusativ' },
          { type: 'text', content: ' Debatte vor. Sie diskutiert ' },
          { type: 'blank', id: 'seminar-6', category: 'verb', answer: 'über die', hint: 'diskutieren über + Akkusativ', explanation: 'diskutieren über = Thema; diskutieren mit = Gesprächspartner.' },
          { type: 'text', content: ' Verantwortung der Entwickler und sucht ' },
          { type: 'blank', id: 'seminar-7', category: 'verb', answer: 'nach einem', hint: 'suchen nach + Dativ' },
          { type: 'text', content: ' klaren Beispiel. Die Notizen hängen ' },
          { type: 'blank', id: 'seminar-8', category: 'location', answer: 'an der', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Tafel. Am Ende besteht Einigkeit ' },
          { type: 'blank', id: 'seminar-9', category: 'noun', answer: 'über die', hint: 'Einigkeit über + Akkusativ' },
          { type: 'text', content: ' zentrale These, aber Zweifel ' },
          { type: 'blank', id: 'seminar-10', category: 'noun', answer: 'an der', hint: 'Zweifel an + Dativ' },
          { type: 'text', content: ' praktischen Umsetzung bleiben.' },
        ],
      },
    ],
  },
  {
    id: 'stadt-ohne-autos',
    title: 'Eine Innenstadt ohne Autos?',
    level: 'B1-B2',
    kind: 'argumentative',
    description: 'Ein kurzer argumentativer Text über Mobilität, Planung und soziale Folgen.',
    focus: ['noun', 'verb', 'location'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Viele Städte diskutieren ' },
          { type: 'blank', id: 'stadt-1', category: 'verb', answer: 'über eine', hint: 'diskutieren über + Akkusativ' },
          { type: 'text', content: ' Innenstadt ohne Autos. Befürworter verweisen ' },
          { type: 'blank', id: 'stadt-2', category: 'verb', answer: 'auf die', hint: 'verweisen auf + Akkusativ' },
          { type: 'text', content: ' bessere Luft und auf mehr Platz ' },
          { type: 'blank', id: 'stadt-3', category: 'noun', answer: 'für die', hint: 'Platz für + Akkusativ' },
          { type: 'text', content: ' Bewohner. Wenn Cafes ihre Tische ' },
          { type: 'blank', id: 'stadt-4', category: 'location', answer: 'auf die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Straße stellen, entsteht ein anderes Gefühl ' },
          { type: 'blank', id: 'stadt-5', category: 'noun', answer: 'von der', hint: 'Gefühl von + Dativ' },
          { type: 'text', content: ' Stadt.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Kritiker warnen jedoch ' },
          { type: 'blank', id: 'stadt-6', category: 'verb', answer: 'vor den', hint: 'warnen vor + Dativ' },
          { type: 'text', content: ' Kosten. Lieferdienste sind abhängig ' },
          { type: 'blank', id: 'stadt-7', category: 'noun', answer: 'von den', hint: 'abhängig von + Dativ' },
          { type: 'text', content: ' Zufahrten, und ältere Menschen brauchen Zugang ' },
          { type: 'blank', id: 'stadt-8', category: 'noun', answer: 'zu den', hint: 'Zugang zu + Dativ' },
          { type: 'text', content: ' Ärzten im Zentrum. Darum sollte die Politik nicht nur Autos ' },
          { type: 'blank', id: 'stadt-9', category: 'location', answer: 'aus der', hint: 'woher? aus + Dativ' },
          { type: 'text', content: ' Innenstadt entfernen, sondern auch Geld ' },
          { type: 'blank', id: 'stadt-10', category: 'verb', answer: 'in den', hint: 'investieren in + Akkusativ' },
          { type: 'text', content: ' Nahverkehr investieren.' },
        ],
      },
    ],
  },
  {
    id: 'arbeitsplatz-im-wandel',
    title: 'Der Arbeitsplatz im Wandel',
    level: 'B2',
    kind: 'expository',
    description: 'Ein beruflicher Kontext mit Verantwortung, Abhängigkeit und räumlicher Organisation.',
    focus: ['verb', 'noun', 'location'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Im neuen Büro arbeitet das Team nicht mehr fest ' },
          { type: 'blank', id: 'arbeit-1', category: 'location', answer: 'an einem', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Platz. Wer konzentriert schreiben will, setzt sich ' },
          { type: 'blank', id: 'arbeit-2', category: 'location', answer: 'in den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' ruhigen Raum. Die Leitung achtet ' },
          { type: 'blank', id: 'arbeit-3', category: 'verb', answer: 'auf die', hint: 'achten auf + Akkusativ' },
          { type: 'text', content: ' Bedürfnisse der Mitarbeitenden und spricht regelmäßig ' },
          { type: 'blank', id: 'arbeit-4', category: 'verb', answer: 'mit dem', hint: 'sprechen mit + Dativ' },
          { type: 'text', content: ' Betriebsrat.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Trotzdem gibt es Kritik ' },
          { type: 'blank', id: 'arbeit-5', category: 'noun', answer: 'an der', hint: 'Kritik an + Dativ' },
          { type: 'text', content: ' neuen Ordnung. Manche haben Sorge ' },
          { type: 'blank', id: 'arbeit-6', category: 'noun', answer: 'um ihre', hint: 'Sorge um + Akkusativ' },
          { type: 'text', content: ' Privatsphäre, andere freuen sich ' },
          { type: 'blank', id: 'arbeit-7', category: 'verb', answer: 'über die', hint: 'sich freuen über + Akkusativ', explanation: 'sich freuen über = Reaktion auf etwas Vorhandenes; sich freuen auf = Erwartung.' },
          { type: 'text', content: ' flexiblen Zonen. Ein Bildschirm hängt ' },
          { type: 'blank', id: 'arbeit-8', category: 'location', answer: 'zwischen den', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Konferenzräumen und informiert ' },
          { type: 'blank', id: 'arbeit-9', category: 'verb', answer: 'über die', hint: 'informieren über + Akkusativ' },
          { type: 'text', content: ' freien Plätze. Der Erfolg hängt schließlich ' },
          { type: 'blank', id: 'arbeit-10', category: 'verb', answer: 'von der', hint: 'abhängen von + Dativ' },
          { type: 'text', content: ' gemeinsamen Nutzung ab.' },
        ],
      },
    ],
  },
  {
    id: 'nachhaltiger-konsum',
    title: 'Nachhaltiger Konsum im Alltag',
    level: 'B1-B2',
    kind: 'argumentative',
    description: 'Ein reflektierender Text über Konsum, Verantwortung und konkrete Alltagssituationen.',
    focus: ['noun', 'verb', 'location'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Wer nachhaltig leben möchte, denkt oft zuerst ' },
          { type: 'blank', id: 'konsum-1', category: 'verb', answer: 'an den', hint: 'denken an + Akkusativ' },
          { type: 'text', content: ' Einkauf. Obst liegt besser lose ' },
          { type: 'blank', id: 'konsum-2', category: 'location', answer: 'in der', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Tasche als in Plastik. Viele Menschen haben Interesse ' },
          { type: 'blank', id: 'konsum-3', category: 'noun', answer: 'an einer', hint: 'Interesse an + Dativ' },
          { type: 'text', content: ' fairen Produktion, aber sie achten im Laden stärker ' },
          { type: 'blank', id: 'konsum-4', category: 'verb', answer: 'auf den', hint: 'achten auf + Akkusativ' },
          { type: 'text', content: ' Preis.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Das Problem besteht nicht nur ' },
          { type: 'blank', id: 'konsum-5', category: 'verb', answer: 'aus den', hint: 'bestehen aus + Dativ' },
          { type: 'text', content: ' Verpackungen. Es geht auch ' },
          { type: 'blank', id: 'konsum-6', category: 'verb', answer: 'um die', hint: 'gehen um + Akkusativ' },
          { type: 'text', content: ' Gewohnheit, Dinge sofort zu ersetzen. Ein Reparaturcafe bietet Hilfe ' },
          { type: 'blank', id: 'konsum-7', category: 'noun', answer: 'bei der', hint: 'Hilfe bei + Dativ' },
          { type: 'text', content: ' Reparatur an und stellt Werkzeuge ' },
          { type: 'blank', id: 'konsum-8', category: 'location', answer: 'auf den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' großen Tisch. So entsteht Verantwortung ' },
          { type: 'blank', id: 'konsum-9', category: 'noun', answer: 'für die', hint: 'Verantwortung für + Akkusativ' },
          { type: 'text', content: ' eigenen Entscheidungen und Respekt ' },
          { type: 'blank', id: 'konsum-10', category: 'noun', answer: 'vor den', hint: 'Respekt vor + Dativ' },
          { type: 'text', content: ' Ressourcen.' },
        ],
      },
    ],
  },
  {
    id: 'museum-der-erinnerung',
    title: 'Im Museum der Erinnerung',
    level: 'B1',
    kind: 'narrative',
    description: 'Ein Museumsbesuch mit Ort, Richtung, Interesse und Erklärsituationen.',
    focus: ['location', 'noun', 'verb'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Die Klasse geht ' },
          { type: 'blank', id: 'museum-1', category: 'location', answer: 'in das', hint: 'wohin? + Akkusativ', acceptedAnswers: ['ins'] },
          { type: 'text', content: ' Stadtmuseum. Gleich am Eingang hängt ein altes Foto ' },
          { type: 'blank', id: 'museum-2', category: 'location', answer: 'über der', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Kasse. Die Schüler stellen sich ' },
          { type: 'blank', id: 'museum-3', category: 'location', answer: 'vor die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Vitrine und hören ' },
          { type: 'blank', id: 'museum-4', category: 'verb', answer: 'auf die', hint: 'hören auf + Akkusativ' },
          { type: 'text', content: ' Erklärung der Führerin.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Besonders groß ist ihr Interesse ' },
          { type: 'blank', id: 'museum-5', category: 'noun', answer: 'an den', hint: 'Interesse an + Dativ' },
          { type: 'text', content: ' Briefen aus der Nachkriegszeit. Eine Schülerin fragt ' },
          { type: 'blank', id: 'museum-6', category: 'verb', answer: 'nach dem', hint: 'fragen nach + Dativ' },
          { type: 'text', content: ' Alltag der Familien. Die Führerin zeigt ' },
          { type: 'blank', id: 'museum-7', category: 'location', answer: 'auf eine', hint: 'wohin?/Richtung: auf + Akkusativ' },
          { type: 'text', content: ' Karte und spricht ' },
          { type: 'blank', id: 'museum-8', category: 'verb', answer: 'über die', hint: 'sprechen über + Akkusativ', explanation: 'sprechen über = Thema; sprechen mit = Gesprächspartner.' },
          { type: 'text', content: ' zerstörten Straßen. Am Ende bleibt ein Gefühl ' },
          { type: 'blank', id: 'museum-9', category: 'noun', answer: 'für die', hint: 'Gefühl für + Akkusativ' },
          { type: 'text', content: ' Nähe der Geschichte und Dankbarkeit ' },
          { type: 'blank', id: 'museum-10', category: 'noun', answer: 'für den', hint: 'Dankbarkeit für + Akkusativ' },
          { type: 'text', content: ' Frieden.' },
        ],
      },
    ],
  },
  {
    id: 'pruefungsvorbereitung',
    title: 'Der Tag vor der Prüfung',
    level: 'B1-B2',
    kind: 'narrative',
    description: 'Eine realistische Lernszene mit Vorbereitung, Angst, Ordnung und konkreter Raumlogik.',
    focus: ['verb', 'noun', 'location'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Am Abend vor der Prüfung bereitet sich Samira ' },
          { type: 'blank', id: 'pruefung-1', category: 'verb', answer: 'auf den', hint: 'sich vorbereiten auf + Akkusativ' },
          { type: 'text', content: ' mündlichen Teil vor. Sie legt ihre Karteikarten ' },
          { type: 'blank', id: 'pruefung-2', category: 'location', answer: 'auf den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Tisch und schreibt schwierige Wörter ' },
          { type: 'blank', id: 'pruefung-3', category: 'location', answer: 'an die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Wand. Trotz ihrer Angst ' },
          { type: 'blank', id: 'pruefung-4', category: 'noun', answer: 'vor der', hint: 'Angst vor + Dativ' },
          { type: 'text', content: ' Prüfung glaubt sie ' },
          { type: 'blank', id: 'pruefung-5', category: 'verb', answer: 'an ihre', hint: 'glauben an + Akkusativ' },
          { type: 'text', content: ' Fortschritte.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Ihr Bruder fragt ' },
          { type: 'blank', id: 'pruefung-6', category: 'verb', answer: 'nach den', hint: 'fragen nach + Dativ' },
          { type: 'text', content: ' Themen und hilft ihr ' },
          { type: 'blank', id: 'pruefung-7', category: 'noun', answer: 'bei der', hint: 'Hilfe bei + Dativ' },
          { type: 'text', content: ' Wiederholung. Samira setzt sich nicht ' },
          { type: 'blank', id: 'pruefung-8', category: 'location', answer: 'vor den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Fernseher, sondern bleibt konzentriert ' },
          { type: 'blank', id: 'pruefung-9', category: 'location', answer: 'an dem', hint: 'wo? + Dativ', acceptedAnswers: ['am'] },
          { type: 'text', content: ' Schreibtisch. Kurz vor dem Schlafen freut sie sich sogar ' },
          { type: 'blank', id: 'pruefung-10', category: 'verb', answer: 'auf das', hint: 'sich freuen auf + Akkusativ', explanation: 'sich freuen auf = Erwartung; sich freuen über = Freude über etwas, das schon da ist.' },
          { type: 'text', content: ' Gespräch.' },
        ],
      },
    ],
  },
  {
    id: 'wohnen-in-der-stadt',
    title: 'Warum Wohnraum knapp wird',
    level: 'B2',
    kind: 'expository',
    description: 'Ein erklärender Text über Wohnungssuche, Stadtentwicklung und soziale Abhängigkeiten.',
    focus: ['noun', 'verb', 'location'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'In vielen Städten steigt die Nachfrage ' },
          { type: 'blank', id: 'wohnen-1', category: 'noun', answer: 'nach den', hint: 'Nachfrage nach + Dativ' },
          { type: 'text', content: ' kleinen Wohnungen. Studierende suchen ' },
          { type: 'blank', id: 'wohnen-2', category: 'verb', answer: 'nach einem', hint: 'suchen nach + Dativ' },
          { type: 'text', content: ' bezahlbaren Zimmer, Familien ziehen ' },
          { type: 'blank', id: 'wohnen-3', category: 'location', answer: 'in die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Randbezirke. Gleichzeitig investieren Unternehmen ' },
          { type: 'blank', id: 'wohnen-4', category: 'verb', answer: 'in die', hint: 'investieren in + Akkusativ' },
          { type: 'text', content: ' Modernisierung alter Häuser.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Der Streit ' },
          { type: 'blank', id: 'wohnen-5', category: 'noun', answer: 'um die', hint: 'Streit um + Akkusativ' },
          { type: 'text', content: ' Mieten wird emotional, weil viele Angst ' },
          { type: 'blank', id: 'wohnen-6', category: 'noun', answer: 'vor der', hint: 'Angst vor + Dativ' },
          { type: 'text', content: ' Verdrängung haben. Einige Politiker setzen Hoffnung ' },
          { type: 'blank', id: 'wohnen-7', category: 'noun', answer: 'auf den', hint: 'Hoffnung auf + Akkusativ' },
          { type: 'text', content: ' Neubau, andere verweisen ' },
          { type: 'blank', id: 'wohnen-8', category: 'verb', answer: 'auf die', hint: 'verweisen auf + Akkusativ' },
          { type: 'text', content: ' leerstehenden Büros. Entscheidend ist der Zugang ' },
          { type: 'blank', id: 'wohnen-9', category: 'noun', answer: 'zu den', hint: 'Zugang zu + Dativ' },
          { type: 'text', content: ' Orten, an denen Menschen arbeiten und lernen; ohne ihn bleibt die Stadt nur ' },
          { type: 'blank', id: 'wohnen-10', category: 'location', answer: 'auf dem', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Papier gerecht.' },
        ],
      },
    ],
  },
  {
    id: 'freizeit-in-den-bergen',
    title: 'Ein Wochenende in den Bergen',
    level: 'B1',
    kind: 'narrative',
    description: 'Eine erwachsene Freizeitszene mit Bewegung, Lage, Wetter und festen Wendungen.',
    focus: ['location', 'verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Am Freitag fahren Nora und Cem ' },
          { type: 'blank', id: 'berge-1', category: 'location', answer: 'in die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Berge. Ihre Pension liegt ' },
          { type: 'blank', id: 'berge-2', category: 'location', answer: 'zwischen den', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Tannen und nicht weit ' },
          { type: 'blank', id: 'berge-3', category: 'location', answer: 'von dem', hint: 'von + Dativ', acceptedAnswers: ['vom'] },
          { type: 'text', content: ' See entfernt. Beim Frühstück sprechen sie ' },
          { type: 'blank', id: 'berge-4', category: 'verb', answer: 'über die', hint: 'sprechen über + Akkusativ' },
          { type: 'text', content: ' Route und entscheiden sich ' },
          { type: 'blank', id: 'berge-5', category: 'verb', answer: 'für den', hint: 'sich entscheiden für + Akkusativ' },
          { type: 'text', content: ' längeren Weg.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Kurz vor dem Gipfel stellen sie die Rucksäcke ' },
          { type: 'blank', id: 'berge-6', category: 'location', answer: 'auf den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Boden und schauen ' },
          { type: 'blank', id: 'berge-7', category: 'location', answer: 'in das', hint: 'Richtung: in + Akkusativ', acceptedAnswers: ['ins'] },
          { type: 'text', content: ' Tal. Cem hat Respekt ' },
          { type: 'blank', id: 'berge-8', category: 'noun', answer: 'vor dem', hint: 'Respekt vor + Dativ' },
          { type: 'text', content: ' steilen Abstieg, aber Nora erinnert ihn ' },
          { type: 'blank', id: 'berge-9', category: 'verb', answer: 'an die', hint: 'erinnern an + Akkusativ' },
          { type: 'text', content: ' gute Ausrüstung. Am Ende sind beide stolz ' },
          { type: 'blank', id: 'berge-10', category: 'noun', answer: 'auf ihre', hint: 'stolz auf + Akkusativ' },
          { type: 'text', content: ' ruhige Entscheidung.' },
        ],
      },
    ],
  },
  {
    id: 'algorithmen-und-aufmerksamkeit',
    title: 'Algorithmen und Aufmerksamkeit',
    level: 'B2',
    kind: 'argumentative',
    description: 'Ein Text über digitale Plattformen, Konzentration und gesellschaftliche Verantwortung.',
    focus: ['verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Digitale Plattformen reagieren sehr schnell ' },
          { type: 'blank', id: 'algo-1', category: 'verb', answer: 'auf das', hint: 'reagieren auf + Akkusativ' },
          { type: 'text', content: ' Verhalten ihrer Nutzer. Wer sich lange ' },
          { type: 'blank', id: 'algo-2', category: 'verb', answer: 'mit einem', hint: 'sich beschäftigen mit + Dativ' },
          { type: 'text', content: ' Thema beschäftigt, bekommt mehr davon angezeigt. Diese Systeme verfügen ' },
          { type: 'blank', id: 'algo-3', category: 'verb', answer: 'über eine', hint: 'verfügen über + Akkusativ' },
          { type: 'text', content: ' enorme Menge an Daten und haben dadurch großen Einfluss ' },
          { type: 'blank', id: 'algo-4', category: 'noun', answer: 'auf die', hint: 'Einfluss auf + Akkusativ' },
          { type: 'text', content: ' öffentliche Aufmerksamkeit.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Das Problem besteht nicht nur ' },
          { type: 'blank', id: 'algo-5', category: 'verb', answer: 'in der', hint: 'bestehen in + Dativ' },
          { type: 'text', content: ' Technik, sondern auch in unseren Gewohnheiten. Viele Menschen konzentrieren sich kaum noch ' },
          { type: 'blank', id: 'algo-6', category: 'verb', answer: 'auf eine', hint: 'sich konzentrieren auf + Akkusativ' },
          { type: 'text', content: ' längere Argumentation, obwohl demokratische Debatten gerade ' },
          { type: 'blank', id: 'algo-7', category: 'noun', answer: 'von der', hint: 'abhängen von + Dativ' },
          { type: 'text', content: ' Fähigkeit zum genauen Lesen abhängen. Daraus folgt Verantwortung ' },
          { type: 'blank', id: 'algo-8', category: 'noun', answer: 'für den', hint: 'Verantwortung für + Akkusativ' },
          { type: 'text', content: ' Umgang mit Aufmerksamkeit und die Suche ' },
          { type: 'blank', id: 'algo-9', category: 'noun', answer: 'nach einer', hint: 'Suche nach + Dativ' },
          { type: 'text', content: ' besseren digitalen Kultur.' },
        ],
      },
    ],
  },
  {
    id: 'wasserstoff-zwischen-hoffnung-und-physik',
    title: 'Wasserstoff zwischen Hoffnung und Physik',
    level: 'B2-C1',
    kind: 'expository',
    description: 'Ein sachlicher Text über Energieumwandlung, Infrastruktur und politische Erwartungen.',
    focus: ['verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Wasserstoff besteht zwar ' },
          { type: 'blank', id: 'wasser-1', category: 'verb', answer: 'aus dem', hint: 'bestehen aus + Dativ' },
          { type: 'text', content: ' häufigsten Element des Universums, muss auf der Erde aber energieintensiv erzeugt werden. Ob grüner Wasserstoff ' },
          { type: 'blank', id: 'wasser-2', category: 'verb', answer: 'zu einer', hint: 'beitragen zu + Dativ' },
          { type: 'text', content: ' klimafreundlichen Industrie beiträgt, hängt stark ' },
          { type: 'blank', id: 'wasser-3', category: 'verb', answer: 'von dem', hint: 'abhängen von + Dativ', acceptedAnswers: ['vom'] },
          { type: 'text', content: ' verfügbaren Strom ab. Gerade Stahlwerke haben Bedarf ' },
          { type: 'blank', id: 'wasser-4', category: 'noun', answer: 'an einer', hint: 'Bedarf an + Dativ' },
          { type: 'text', content: ' Energiequelle, die hohe Temperaturen ermöglicht.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Politische Strategien setzen große Hoffnung ' },
          { type: 'blank', id: 'wasser-5', category: 'noun', answer: 'auf den', hint: 'Hoffnung auf + Akkusativ' },
          { type: 'text', content: ' neuen Energieträger, doch die Entscheidung ' },
          { type: 'blank', id: 'wasser-6', category: 'noun', answer: 'für eine', hint: 'Entscheidung für + Akkusativ' },
          { type: 'text', content: ' Technologie ist nie rein technisch. Sie hängt auch ' },
          { type: 'blank', id: 'wasser-7', category: 'verb', answer: 'mit den', hint: 'zusammenhängen mit + Dativ' },
          { type: 'text', content: ' Preisen, Netzen und internationalen Lieferketten zusammen. Wer über Wasserstoff spricht, sollte daher den Unterschied ' },
          { type: 'blank', id: 'wasser-8', category: 'noun', answer: 'zwischen einer', hint: 'Unterschied zwischen + Dativ' },
          { type: 'text', content: ' realistischen Anwendung und einem bloßen Versprechen kennen.' },
        ],
      },
    ],
  },
  {
    id: 'demokratie-unter-druck',
    title: 'Demokratie unter Druck',
    level: 'B2-C1',
    kind: 'argumentative',
    description: 'Ein Text über Protest, Vertrauen und die Voraussetzungen öffentlicher Debatten.',
    focus: ['verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Bürger protestieren oft ' },
          { type: 'blank', id: 'demo-1', category: 'verb', answer: 'gegen eine', hint: 'protestieren gegen + Akkusativ' },
          { type: 'text', content: ' konkrete Entscheidung, kämpfen aber meist ' },
          { type: 'blank', id: 'demo-2', category: 'verb', answer: 'für ein', hint: 'kämpfen für + Akkusativ' },
          { type: 'text', content: ' größeres Prinzip. Wer sich ' },
          { type: 'blank', id: 'demo-3', category: 'verb', answer: 'für die', hint: 'sich einsetzen für + Akkusativ' },
          { type: 'text', content: ' Pressefreiheit einsetzt, verteidigt nicht nur Journalisten, sondern auch das Recht der Öffentlichkeit ' },
          { type: 'blank', id: 'demo-4', category: 'noun', answer: 'auf eine', hint: 'Recht auf + Akkusativ' },
          { type: 'text', content: ' informierte Entscheidung.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Demokratie lebt ' },
          { type: 'blank', id: 'demo-5', category: 'verb', answer: 'von dem', hint: 'leben von + Dativ', acceptedAnswers: ['vom'] },
          { type: 'text', content: ' Vertrauen ihrer Bürger, leidet aber ' },
          { type: 'blank', id: 'demo-6', category: 'verb', answer: 'unter der', hint: 'leiden unter + Dativ' },
          { type: 'text', content: ' Verachtung gemeinsamer Regeln. Warnungen ' },
          { type: 'blank', id: 'demo-7', category: 'noun', answer: 'vor der', hint: 'Warnung vor + Dativ' },
          { type: 'text', content: ' Polarisierung sind deshalb nicht bloß moralische Appelle. Sie beziehen sich ' },
          { type: 'blank', id: 'demo-8', category: 'verb', answer: 'auf die', hint: 'sich beziehen auf + Akkusativ' },
          { type: 'text', content: ' praktische Frage, ob politische Gegner noch Respekt ' },
          { type: 'blank', id: 'demo-9', category: 'noun', answer: 'vor den', hint: 'Respekt vor + Dativ' },
          { type: 'text', content: ' Institutionen zeigen.' },
        ],
      },
    ],
  },
  {
    id: 'schlaf-und-gesellschaft',
    title: 'Schlaf als öffentliche Frage',
    level: 'B2',
    kind: 'expository',
    description: 'Ein Text über Biologie, Arbeitszeiten und die sozialen Kosten von Müdigkeit.',
    focus: ['verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Schlafmangel führt nicht nur ' },
          { type: 'blank', id: 'schlaf-1', category: 'verb', answer: 'zu einer', hint: 'führen zu + Dativ' },
          { type: 'text', content: ' schlechteren Stimmung, sondern wirkt sich auch ' },
          { type: 'blank', id: 'schlaf-2', category: 'verb', answer: 'auf die', hint: 'sich auswirken auf + Akkusativ' },
          { type: 'text', content: ' Konzentration aus. Wer dauerhaft ' },
          { type: 'blank', id: 'schlaf-3', category: 'verb', answer: 'unter dem', hint: 'leiden unter + Dativ' },
          { type: 'text', content: ' Mangel an Erholung leidet, hat ein höheres Risiko ' },
          { type: 'blank', id: 'schlaf-4', category: 'noun', answer: 'für bestimmte', hint: 'Risiko für + Akkusativ' },
          { type: 'text', content: ' Krankheiten.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Trotzdem wird die Debatte oft ' },
          { type: 'blank', id: 'schlaf-5', category: 'verb', answer: 'auf die', hint: 'verengen auf + Akkusativ' },
          { type: 'text', content: ' persönliche Disziplin verengt. Dabei besteht ein enger Zusammenhang ' },
          { type: 'blank', id: 'schlaf-6', category: 'noun', answer: 'zwischen den', hint: 'Zusammenhang zwischen + Dativ' },
          { type: 'text', content: ' Arbeitszeiten und der Gesundheit. Schulen, Kliniken und Unternehmen könnten stärker ' },
          { type: 'blank', id: 'schlaf-7', category: 'verb', answer: 'zu dem', hint: 'beitragen zu + Dativ', acceptedAnswers: ['zum'] },
          { type: 'text', content: ' Schutz vor Übermüdung beitragen, wenn sie sich ernsthaft ' },
          { type: 'blank', id: 'schlaf-8', category: 'verb', answer: 'mit den', hint: 'sich beschäftigen mit + Dativ' },
          { type: 'text', content: ' biologischen Rhythmen beschäftigen.' },
        ],
      },
    ],
  },
  {
    id: 'labor-und-bewerbung',
    title: 'Bewerbung im Forschungslabor',
    level: 'B1-B2',
    kind: 'narrative',
    description: 'Eine berufliche Szene mit höflichen Routinen und häufigen institutionellen Wendungen.',
    focus: ['verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Nora bewirbt sich ' },
          { type: 'blank', id: 'labor-1', category: 'verb', answer: 'bei einem', hint: 'sich bewerben bei + Dativ' },
          { type: 'text', content: ' Institut ' },
          { type: 'blank', id: 'labor-2', category: 'verb', answer: 'um eine', hint: 'sich bewerben um + Akkusativ' },
          { type: 'text', content: ' Stelle in der Klimaforschung. In ihrem Schreiben bedankt sie sich ' },
          { type: 'blank', id: 'labor-3', category: 'verb', answer: 'für die', hint: 'sich bedanken für + Akkusativ' },
          { type: 'text', content: ' Einladung und entschuldigt sich ' },
          { type: 'blank', id: 'labor-4', category: 'verb', answer: 'für eine', hint: 'sich entschuldigen für + Akkusativ' },
          { type: 'text', content: ' verspätete Antwort.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Im Gespräch fragt die Leiterin ' },
          { type: 'blank', id: 'labor-5', category: 'verb', answer: 'nach ihrer', hint: 'fragen nach + Dativ' },
          { type: 'text', content: ' Erfahrung mit Messgeräten. Nora berichtet ' },
          { type: 'blank', id: 'labor-6', category: 'verb', answer: 'von einem', hint: 'berichten von + Dativ' },
          { type: 'text', content: ' Praktikum und zeigt großes Interesse ' },
          { type: 'blank', id: 'labor-7', category: 'noun', answer: 'an der', hint: 'Interesse an + Dativ' },
          { type: 'text', content: ' Datenanalyse. Einige Tage später erhält sie eine Antwort ' },
          { type: 'blank', id: 'labor-8', category: 'noun', answer: 'auf ihre', hint: 'Antwort auf + Akkusativ' },
          { type: 'text', content: ' Bewerbung und freut sich ' },
          { type: 'blank', id: 'labor-9', category: 'verb', answer: 'auf die', hint: 'sich freuen auf + Akkusativ', explanation: 'sich freuen auf = Erwartung; sich freuen über = Reaktion auf etwas Vorhandenes.' },
          { type: 'text', content: ' Zusammenarbeit.' },
        ],
      },
    ],
  },
  {
    id: 'lesen-der-erde',
    title: 'Die Erde lesen',
    level: 'B2-C1',
    kind: 'expository',
    description: 'Ein geowissenschaftlicher Text über Schichten, Spuren und historische Rekonstruktion.',
    focus: ['verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Geologen schließen ' },
          { type: 'blank', id: 'erde-1', category: 'verb', answer: 'aus den', hint: 'schließen aus + Dativ' },
          { type: 'text', content: ' Schichten eines Gebirges auf Prozesse, die Millionen Jahre zurückliegen. Fossilien weisen ' },
          { type: 'blank', id: 'erde-2', category: 'verb', answer: 'auf eine', hint: 'hinweisen auf + Akkusativ' },
          { type: 'text', content: ' frühere Küste hin, und kleine Unterschiede ' },
          { type: 'blank', id: 'erde-3', category: 'noun', answer: 'zwischen den', hint: 'Unterschied zwischen + Dativ' },
          { type: 'text', content: ' Sedimenten verraten Veränderungen des Klimas.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Wissenschaftliche Erklärungen beruhen selten ' },
          { type: 'blank', id: 'erde-4', category: 'verb', answer: 'auf einem', hint: 'beruhen auf + Dativ' },
          { type: 'text', content: ' einzigen Fund. Erst der Zusammenhang ' },
          { type: 'blank', id: 'erde-5', category: 'noun', answer: 'mit anderen', hint: 'Zusammenhang mit + Dativ' },
          { type: 'text', content: ' Daten liefert einen Beweis ' },
          { type: 'blank', id: 'erde-6', category: 'noun', answer: 'für eine', hint: 'Beweis für + Akkusativ' },
          { type: 'text', content: ' plausible Rekonstruktion. Gute Forschung unterscheidet daher streng ' },
          { type: 'blank', id: 'erde-7', category: 'verb', answer: 'zwischen einer', hint: 'unterscheiden zwischen + Dativ' },
          { type: 'text', content: ' Spur, einer Hypothese und einer belastbaren Aussage.' },
        ],
      },
    ],
  },
  {
    id: 'energiepolitik-und-verteilung',
    title: 'Energiepolitik und Verteilung',
    level: 'B2-C1',
    kind: 'argumentative',
    description: 'Ein Text über Infrastruktur, soziale Kosten und politische Zielkonflikte.',
    focus: ['verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Eine Regierung kann sich ' },
          { type: 'blank', id: 'energie-1', category: 'verb', answer: 'für einen', hint: 'sich entscheiden für + Akkusativ' },
          { type: 'text', content: ' schnellen Ausbau erneuerbarer Energien entscheiden, muss sich aber zugleich ' },
          { type: 'blank', id: 'energie-2', category: 'verb', answer: 'mit den', hint: 'sich beschäftigen mit + Dativ' },
          { type: 'text', content: ' sozialen Folgen beschäftigen. Hohe Preise führen ' },
          { type: 'blank', id: 'energie-3', category: 'verb', answer: 'zu einer', hint: 'führen zu + Dativ' },
          { type: 'text', content: ' Debatte über Gerechtigkeit und wecken Kritik ' },
          { type: 'blank', id: 'energie-4', category: 'noun', answer: 'an einer', hint: 'Kritik an + Dativ' },
          { type: 'text', content: ' Politik, die Lasten ungleich verteilt.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Wer Geld ' },
          { type: 'blank', id: 'energie-5', category: 'verb', answer: 'in die', hint: 'investieren in + Akkusativ' },
          { type: 'text', content: ' Netze investiert, sorgt ' },
          { type: 'blank', id: 'energie-6', category: 'verb', answer: 'für eine', hint: 'sorgen für + Akkusativ' },
          { type: 'text', content: ' robustere Versorgung. Doch der Streit ' },
          { type: 'blank', id: 'energie-7', category: 'noun', answer: 'um die', hint: 'Streit um + Akkusativ' },
          { type: 'text', content: ' Kosten bleibt, solange kein breiter Konsens ' },
          { type: 'blank', id: 'energie-8', category: 'noun', answer: 'über die', hint: 'Konsens über + Akkusativ' },
          { type: 'text', content: ' Verteilung entsteht. Gute Politik verbindet deshalb Verantwortung ' },
          { type: 'blank', id: 'energie-9', category: 'noun', answer: 'für das', hint: 'Verantwortung für + Akkusativ' },
          { type: 'text', content: ' Klima mit Aufmerksamkeit für soziale Härten.' },
        ],
      },
    ],
  },
  {
    id: 'lernen-und-irrtum',
    title: 'Lernen aus Irrtümern',
    level: 'B2-C1',
    kind: 'argumentative',
    description: 'Ein reflexiver Text über Erkenntnis, Zweifel und intellektuelle Bescheidenheit.',
    focus: ['verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Wissenschaft beginnt oft damit, ' },
          { type: 'blank', id: 'lernen-1', category: 'verb', answer: 'an einer', hint: 'zweifeln an + Dativ' },
          { type: 'text', content: ' vertrauten Erklärung zu zweifeln. Wer dagegen ' },
          { type: 'blank', id: 'lernen-2', category: 'verb', answer: 'auf einer', hint: 'bestehen auf + Dativ' },
          { type: 'text', content: ' unhaltbaren Behauptung besteht, verwechselt Überzeugung mit Wahrheit. Erkenntnis braucht die Bereitschaft ' },
          { type: 'blank', id: 'lernen-3', category: 'noun', answer: 'zu einer', hint: 'Bereitschaft zu + Dativ' },
          { type: 'text', content: ' Korrektur und den Mut ' },
          { type: 'blank', id: 'lernen-4', category: 'noun', answer: 'zu einem', hint: 'Mut zu + Dativ' },
          { type: 'text', content: ' neuen Versuch.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Auch im Alltag bemühen sich Menschen ' },
          { type: 'blank', id: 'lernen-5', category: 'verb', answer: 'um eine', hint: 'sich bemühen um + Akkusativ' },
          { type: 'text', content: ' bessere Entscheidung, ohne sofort Gewissheit zu haben. Eine gute Frage richtet sich nicht nur ' },
          { type: 'blank', id: 'lernen-6', category: 'verb', answer: 'nach dem', hint: 'sich richten nach + Dativ' },
          { type: 'text', content: ' Ergebnis, sondern auch ' },
          { type: 'blank', id: 'lernen-7', category: 'verb', answer: 'nach den', hint: 'sich richten nach + Dativ' },
          { type: 'text', content: ' Gründen. Deshalb ist das Verhältnis ' },
          { type: 'blank', id: 'lernen-8', category: 'noun', answer: 'zu dem', hint: 'Verhältnis zu + Dativ', acceptedAnswers: ['zum'] },
          { type: 'text', content: ' eigenen Irrtum ein Maß intellektueller Reife.' },
        ],
      },
    ],
  },
  {
    id: 'migration-und-stadt',
    title: 'Migration und Stadt',
    level: 'B2',
    kind: 'expository',
    description: 'Ein sozialwissenschaftlicher Text über Teilhabe, Infrastruktur und Zugehörigkeit.',
    focus: ['verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Ob Menschen erfolgreich ' },
          { type: 'blank', id: 'migration-1', category: 'verb', answer: 'an dem', hint: 'teilnehmen an + Dativ', acceptedAnswers: ['am'] },
          { type: 'text', content: ' Leben einer Stadt teilnehmen, hängt nicht allein von ihrer Motivation ab. Entscheidend sind Zugang ' },
          { type: 'blank', id: 'migration-2', category: 'noun', answer: 'zu den', hint: 'Zugang zu + Dativ' },
          { type: 'text', content: ' Schulen, Kontakt ' },
          { type: 'blank', id: 'migration-3', category: 'noun', answer: 'zu den', hint: 'Kontakt zu + Dativ' },
          { type: 'text', content: ' Nachbarn und Hilfe ' },
          { type: 'blank', id: 'migration-4', category: 'noun', answer: 'bei der', hint: 'Hilfe bei + Dativ' },
          { type: 'text', content: ' Wohnungssuche.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Städte profitieren ' },
          { type: 'blank', id: 'migration-5', category: 'verb', answer: 'von den', hint: 'profitieren von + Dativ' },
          { type: 'text', content: ' Erfahrungen neuer Bewohner, wenn Institutionen nicht nur ' },
          { type: 'blank', id: 'migration-6', category: 'verb', answer: 'über Integration', hint: 'sprechen über + Akkusativ' },
          { type: 'text', content: ' sprechen, sondern auch ' },
          { type: 'blank', id: 'migration-7', category: 'verb', answer: 'mit den', hint: 'sprechen mit + Dativ' },
          { type: 'text', content: ' Betroffenen. Zugehörigkeit entsteht weniger ' },
          { type: 'blank', id: 'migration-8', category: 'verb', answer: 'durch die', hint: 'entstehen durch + Akkusativ' },
          { type: 'text', content: ' Behauptung einer gemeinsamen Identität als durch die Chance ' },
          { type: 'blank', id: 'migration-9', category: 'noun', answer: 'auf eine', hint: 'Chance auf + Akkusativ' },
          { type: 'text', content: ' sichtbare Beteiligung.' },
        ],
      },
    ],
  },
  {
    id: 'freundschaft-und-alltag',
    title: 'Freundschaft im Alltag',
    level: 'B1',
    kind: 'narrative',
    description: 'Eine erwachsene Alltagsszene mit besonders häufigen sozialen Wendungen.',
    focus: ['verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Nach der Arbeit trifft sich Elena ' },
          { type: 'blank', id: 'freund-1', category: 'verb', answer: 'mit einer', hint: 'sich treffen mit + Dativ' },
          { type: 'text', content: ' Freundin. Sie fangen ' },
          { type: 'blank', id: 'freund-2', category: 'verb', answer: 'mit einem', hint: 'anfangen mit + Dativ' },
          { type: 'text', content: ' Kaffee an, hören aber bald ' },
          { type: 'blank', id: 'freund-3', category: 'verb', answer: 'mit dem', hint: 'aufhören mit + Dativ' },
          { type: 'text', content: ' Small Talk auf und sprechen über ihre Pläne. Elena interessiert sich ' },
          { type: 'blank', id: 'freund-4', category: 'verb', answer: 'für die', hint: 'sich interessieren für + Akkusativ' },
          { type: 'text', content: ' neue Weiterbildung ihrer Freundin, ärgert sich aber ' },
          { type: 'blank', id: 'freund-5', category: 'verb', answer: 'über die', hint: 'sich ärgern über + Akkusativ' },
          { type: 'text', content: ' hohen Gebühren.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Später gratuliert sie ihr ' },
          { type: 'blank', id: 'freund-6', category: 'verb', answer: 'zu dem', hint: 'gratulieren zu + Dativ', acceptedAnswers: ['zum'] },
          { type: 'text', content: ' bestandenen Examen. Beide träumen ' },
          { type: 'blank', id: 'freund-7', category: 'verb', answer: 'von einer', hint: 'träumen von + Dativ' },
          { type: 'text', content: ' ruhigeren Stadt und lachen ' },
          { type: 'blank', id: 'freund-8', category: 'verb', answer: 'über einen', hint: 'lachen über + Akkusativ' },
          { type: 'text', content: ' absurden Werbeslogan. Ihre Freundschaft gehört ' },
          { type: 'blank', id: 'freund-9', category: 'verb', answer: 'zu den', hint: 'gehören zu + Dativ' },
          { type: 'text', content: ' wenigen Dingen, auf die beide sich verlassen. Beim Abschied bedankt sich Elena ' },
          { type: 'blank', id: 'freund-10', category: 'verb', answer: 'für die', hint: 'sich bedanken für + Akkusativ' },
          { type: 'text', content: ' Einladung und empfindet echte Freude ' },
          { type: 'blank', id: 'freund-11', category: 'noun', answer: 'an dem', hint: 'Freude an + Dativ', acceptedAnswers: ['am'] },
          { type: 'text', content: ' langen Gespräch.' },
        ],
      },
    ],
  },
  {
    id: 'praevention-und-evidenz',
    title: 'Prävention und Evidenz',
    level: 'B2',
    kind: 'expository',
    description: 'Ein medizinischer Text über Forschung, Empfehlungen und differenzierte Urteile.',
    focus: ['verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Viele Menschen informieren sich ' },
          { type: 'blank', id: 'praev-1', category: 'verb', answer: 'über die', hint: 'sich informieren über + Akkusativ' },
          { type: 'text', content: ' Wirkung neuer Nahrungsergänzungsmittel und wundern sich ' },
          { type: 'blank', id: 'praev-2', category: 'verb', answer: 'über die', hint: 'sich wundern über + Akkusativ' },
          { type: 'text', content: ' widersprüchlichen Ratschläge. Tatsächlich unterscheiden sich einzelne Studien stark ' },
          { type: 'blank', id: 'praev-3', category: 'verb', answer: 'von den', hint: 'sich unterscheiden von + Dativ' },
          { type: 'text', content: ' Ergebnissen größerer Übersichten. Eine mögliche Ursache ' },
          { type: 'blank', id: 'praev-4', category: 'noun', answer: 'für die', hint: 'Ursache für + Akkusativ' },
          { type: 'text', content: ' Abweichung liegt in kleinen Stichproben.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Für manche Patienten eignet sich ein Medikament gut ' },
          { type: 'blank', id: 'praev-5', category: 'verb', answer: 'für die', hint: 'sich eignen für + Akkusativ' },
          { type: 'text', content: ' Behandlung, während andere lieber ' },
          { type: 'blank', id: 'praev-6', category: 'verb', answer: 'auf bestimmte', hint: 'verzichten auf + Akkusativ' },
          { type: 'text', content: ' Präparate verzichten sollten. Schutz ' },
          { type: 'blank', id: 'praev-7', category: 'noun', answer: 'vor einer', hint: 'Schutz vor + Dativ' },
          { type: 'text', content: ' Krankheit entsteht selten durch eine einzelne Maßnahme; oft braucht es eine Lösung ' },
          { type: 'blank', id: 'praev-8', category: 'noun', answer: 'für mehrere', hint: 'Lösung für + Akkusativ' },
          { type: 'text', content: ' Risikofaktoren und ein Gespräch ' },
          { type: 'blank', id: 'praev-9', category: 'noun', answer: 'mit einer', hint: 'Gespräch mit + Dativ' },
          { type: 'text', content: ' Fachperson.' },
        ],
      },
    ],
  },
  {
    id: 'pflege-und-genesung',
    title: 'Pflege und Genesung',
    level: 'B1-B2',
    kind: 'expository',
    description: 'Ein Text über Betreuung, Kommunikation und häufige Wendungen im Gesundheitswesen.',
    focus: ['verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Wer länger krank ist, leidet manchmal ' },
          { type: 'blank', id: 'pflege-1', category: 'verb', answer: 'an einer', hint: 'leiden an + Dativ' },
          { type: 'text', content: ' chronischen Erkrankung und braucht Menschen, die sich zuverlässig ' },
          { type: 'blank', id: 'pflege-2', category: 'verb', answer: 'um die', hint: 'sich kümmern um + Akkusativ' },
          { type: 'text', content: ' Versorgung kümmern. Nach einer Operation erholen sich Patienten oft langsamer ' },
          { type: 'blank', id: 'pflege-3', category: 'verb', answer: 'von dem', hint: 'sich erholen von + Dativ', acceptedAnswers: ['vom'] },
          { type: 'text', content: ' Eingriff, als sie erwartet hatten. Gute Pflege hat deshalb eine direkte Wirkung ' },
          { type: 'blank', id: 'pflege-4', category: 'noun', answer: 'auf die', hint: 'Wirkung auf + Akkusativ' },
          { type: 'text', content: ' Genesung.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Ärzte laden Angehörige manchmal ' },
          { type: 'blank', id: 'pflege-5', category: 'verb', answer: 'zu einem', hint: 'einladen zu + Dativ' },
          { type: 'text', content: ' Gespräch ein, weil Erfahrung ' },
          { type: 'blank', id: 'pflege-6', category: 'noun', answer: 'mit dem', hint: 'Erfahrung mit + Dativ' },
          { type: 'text', content: ' Alltag des Patienten wichtige Hinweise liefert. Eine höfliche Bitte ' },
          { type: 'blank', id: 'pflege-7', category: 'noun', answer: 'um mehr', hint: 'Bitte um + Akkusativ' },
          { type: 'text', content: ' Geduld kann Konflikte vermeiden. Wenn ein Termin verschoben wird, entschuldigt sich die Klinik idealerweise nicht nur ' },
          { type: 'blank', id: 'pflege-8', category: 'verb', answer: 'für die', hint: 'sich entschuldigen für + Akkusativ' },
          { type: 'text', content: ' Verzögerung, sondern auch ' },
          { type: 'blank', id: 'pflege-9', category: 'verb', answer: 'bei den', hint: 'sich entschuldigen bei + Dativ' },
          { type: 'text', content: ' Betroffenen.' },
        ],
      },
    ],
  },
]

export const getPrepositionStoryById = (id: string) =>
  prepositionStories.find((story) => story.id === id)

export const getPrepositionBlanks = (story: PrepositionStory): PrepositionBlankPart[] =>
  story.paragraphs.flatMap((paragraph) =>
    paragraph.parts.filter((part): part is PrepositionBlankPart => part.type === 'blank')
  )

export const countPrepositionBlanksByCategory = (story: PrepositionStory) => {
  const counts: Record<PrepositionCategory, number> = {
    verb: 0,
    location: 0,
    noun: 0,
  }

  getPrepositionBlanks(story).forEach((blank) => {
    counts[blank.category] += 1
  })

  return counts
}
