import type {
  PrepositionBlankPart,
  PrepositionCategory,
  PrepositionStory,
} from '@shared/types'

export const prepositionStories: PrepositionStory[] = [
  {
    id: 'umzug-mit-system',
    title: 'Ein Umzug mit System',
    level: 'B1',
    kind: 'narrative',
    description: 'Eine ruhige Alltagsszene mit Richtungs- und Ortswechseln, ergänzt durch feste Verbindungen.',
    focus: ['location', 'verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Mira zieht am Samstag ' },
          { type: 'blank', id: 'umzug-1', category: 'location', answer: 'in die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' neue Wohnung. Schon früh stellt sie die Kartons ' },
          { type: 'blank', id: 'umzug-2', category: 'location', answer: 'neben die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Tür und hängt den Kalender ' },
          { type: 'blank', id: 'umzug-3', category: 'location', answer: 'an die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Wand. Ihr Bruder wartet ' },
          { type: 'blank', id: 'umzug-4', category: 'verb', answer: 'auf den', hint: 'warten auf + Akkusativ' },
          { type: 'text', content: ' Aufzug, während Mira sich ' },
          { type: 'blank', id: 'umzug-5', category: 'verb', answer: 'über die', hint: 'sich freuen über + Akkusativ', explanation: 'sich freuen über = jetzt froh sein; sich freuen auf = etwas Zukünftiges erwarten.' },
          { type: 'text', content: ' helle Küche freut.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Nach zwei Stunden steht der Schreibtisch ' },
          { type: 'blank', id: 'umzug-6', category: 'location', answer: 'vor dem', hint: 'wo? + Dativ', acceptedAnswers: ['vorm'] },
          { type: 'text', content: ' Fenster, die Lampe liegt noch ' },
          { type: 'blank', id: 'umzug-7', category: 'location', answer: 'unter dem', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Sofa. Beim Auspacken spricht Mira ' },
          { type: 'blank', id: 'umzug-8', category: 'verb', answer: 'mit dem', hint: 'sprechen mit + Dativ' },
          { type: 'text', content: ' Vermieter über den Keller. Am Abend hat sie endlich Vertrauen ' },
          { type: 'blank', id: 'umzug-9', category: 'noun', answer: 'in die', hint: 'Vertrauen in + Akkusativ' },
          { type: 'text', content: ' neue Ordnung und große Lust ' },
          { type: 'blank', id: 'umzug-10', category: 'noun', answer: 'auf den', hint: 'Lust auf + Akkusativ' },
          { type: 'text', content: ' ersten Kaffee am eigenen Tisch.' },
        ],
      },
    ],
  },
  {
    id: 'bahnhof-im-nebel',
    title: 'Orientierung am Bahnhof',
    level: 'A2-B1',
    kind: 'narrative',
    description: 'Eine Reiseepisode mit Wechselpräpositionen, Warte-Situationen und typischen Nomenverbindungen.',
    focus: ['location', 'verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Jonas kommt zu spät ' },
          { type: 'blank', id: 'bahnhof-1', category: 'location', answer: 'an den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Bahnhof. Sein Zug steht schon ' },
          { type: 'blank', id: 'bahnhof-2', category: 'location', answer: 'auf dem', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Gleis 7. Er denkt ' },
          { type: 'blank', id: 'bahnhof-3', category: 'verb', answer: 'an die', hint: 'denken an + Akkusativ', explanation: 'denken an = sich erinnern; denken über = eine Meinung bilden.' },
          { type: 'text', content: ' Fahrkarte, die noch ' },
          { type: 'blank', id: 'bahnhof-4', category: 'location', answer: 'in der', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Jackentasche steckt. Eine Durchsage warnt ' },
          { type: 'blank', id: 'bahnhof-5', category: 'verb', answer: 'vor dem', hint: 'warnen vor + Dativ' },
          { type: 'text', content: ' Ausfall eines Regionalzugs.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Auf dem Bahnsteig bittet er eine Mitarbeiterin ' },
          { type: 'blank', id: 'bahnhof-6', category: 'verb', answer: 'um eine', hint: 'bitten um + Akkusativ' },
          { type: 'text', content: ' Auskunft. Seine Sorge ' },
          { type: 'blank', id: 'bahnhof-7', category: 'noun', answer: 'um den', hint: 'Sorge um + Akkusativ' },
          { type: 'text', content: ' Anschluss ist berechtigt, denn der Bus fährt gleich ' },
          { type: 'blank', id: 'bahnhof-8', category: 'location', answer: 'vor dem', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Haupteingang ab. Schließlich steigt Jonas ' },
          { type: 'blank', id: 'bahnhof-9', category: 'location', answer: 'in den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Zug und hat trotz allem Hoffnung ' },
          { type: 'blank', id: 'bahnhof-10', category: 'noun', answer: 'auf eine', hint: 'Hoffnung auf + Akkusativ' },
          { type: 'text', content: ' pünktliche Ankunft.' },
        ],
      },
    ],
  },
  {
    id: 'sprechstunde',
    title: 'In der Sprechstunde',
    level: 'B1',
    kind: 'narrative',
    description: 'Ein Arzttermin mit körperlichen Beschwerden, Raumangaben und Beratungsverben.',
    focus: ['verb', 'location', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Lea wartet ' },
          { type: 'blank', id: 'arzt-1', category: 'verb', answer: 'auf den', hint: 'warten auf + Akkusativ' },
          { type: 'text', content: ' Arzt und setzt sich ' },
          { type: 'blank', id: 'arzt-2', category: 'location', answer: 'neben die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' ältere Dame. Ihre Angst ' },
          { type: 'blank', id: 'arzt-3', category: 'noun', answer: 'vor der', hint: 'Angst vor + Dativ' },
          { type: 'text', content: ' Untersuchung wird kleiner, als die Ärztin ruhig ' },
          { type: 'blank', id: 'arzt-4', category: 'verb', answer: 'mit ihr', hint: 'sprechen mit + Dativ' },
          { type: 'text', content: ' spricht. Das Rezept liegt bereits ' },
          { type: 'blank', id: 'arzt-5', category: 'location', answer: 'auf dem', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Schreibtisch.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Die Ärztin fragt Lea ' },
          { type: 'blank', id: 'arzt-6', category: 'verb', answer: 'nach den', hint: 'fragen nach + Dativ' },
          { type: 'text', content: ' Symptomen und rät ihr ' },
          { type: 'blank', id: 'arzt-7', category: 'verb', answer: 'zu einer', hint: 'raten zu + Dativ' },
          { type: 'text', content: ' Pause. Lea hat Vertrauen ' },
          { type: 'blank', id: 'arzt-8', category: 'noun', answer: 'zu der', hint: 'Vertrauen zu + Dativ', acceptedAnswers: ['zur'], explanation: 'Vertrauen zu betont die Person; Vertrauen in betont eher Fähigkeit oder System.' },
          { type: 'text', content: ' Ärztin. Zu Hause legt sie die Medikamente ' },
          { type: 'blank', id: 'arzt-9', category: 'location', answer: 'in den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Küchenschrank und achtet in den nächsten Tagen ' },
          { type: 'blank', id: 'arzt-10', category: 'verb', answer: 'auf ihre', hint: 'achten auf + Akkusativ' },
          { type: 'text', content: ' Gesundheit.' },
        ],
      },
    ],
  },
  {
    id: 'seminar-kunstliche-intelligenz',
    title: 'Ein Seminar über künstliche Intelligenz',
    level: 'B2',
    kind: 'expository',
    description: 'Ein sachlicher Text über ein Universitätsseminar, Diskussion und Vorbereitung.',
    focus: ['verb', 'noun', 'location'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Im Seminar beschäftigen sich die Studierenden ' },
          { type: 'blank', id: 'seminar-1', category: 'verb', answer: 'mit den', hint: 'sich beschäftigen mit + Dativ' },
          { type: 'text', content: ' Folgen künstlicher Intelligenz. Die Dozentin legt ein Diagramm ' },
          { type: 'blank', id: 'seminar-2', category: 'location', answer: 'auf den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Tisch und verweist ' },
          { type: 'blank', id: 'seminar-3', category: 'verb', answer: 'auf die', hint: 'verweisen auf + Akkusativ' },
          { type: 'text', content: ' aktuellen Zahlen. Viele haben Interesse ' },
          { type: 'blank', id: 'seminar-4', category: 'noun', answer: 'an der', hint: 'Interesse an + Dativ' },
          { type: 'text', content: ' Frage, ob Software gerechter entscheiden kann als Menschen.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Eine Gruppe bereitet sich ' },
          { type: 'blank', id: 'seminar-5', category: 'verb', answer: 'auf die', hint: 'sich vorbereiten auf + Akkusativ' },
          { type: 'text', content: ' Debatte vor. Sie diskutiert ' },
          { type: 'blank', id: 'seminar-6', category: 'verb', answer: 'über die', hint: 'diskutieren über + Akkusativ', explanation: 'diskutieren über = Thema; diskutieren mit = Gesprächspartner.' },
          { type: 'text', content: ' Verantwortung der Entwickler und sucht ' },
          { type: 'blank', id: 'seminar-7', category: 'verb', answer: 'nach einem', hint: 'suchen nach + Dativ' },
          { type: 'text', content: ' klaren Beispiel. Die Notizen hängen ' },
          { type: 'blank', id: 'seminar-8', category: 'location', answer: 'an der', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Tafel. Am Ende besteht Einigkeit ' },
          { type: 'blank', id: 'seminar-9', category: 'noun', answer: 'über die', hint: 'Einigkeit über + Akkusativ' },
          { type: 'text', content: ' zentrale These, aber Zweifel ' },
          { type: 'blank', id: 'seminar-10', category: 'noun', answer: 'an der', hint: 'Zweifel an + Dativ' },
          { type: 'text', content: ' praktischen Umsetzung bleiben.' },
        ],
      },
    ],
  },
  {
    id: 'stadt-ohne-autos',
    title: 'Eine Innenstadt ohne Autos?',
    level: 'B1-B2',
    kind: 'argumentative',
    description: 'Ein kurzer argumentativer Text über Mobilität, Planung und soziale Folgen.',
    focus: ['noun', 'verb', 'location'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Viele Städte diskutieren ' },
          { type: 'blank', id: 'stadt-1', category: 'verb', answer: 'über eine', hint: 'diskutieren über + Akkusativ' },
          { type: 'text', content: ' Innenstadt ohne Autos. Befürworter verweisen ' },
          { type: 'blank', id: 'stadt-2', category: 'verb', answer: 'auf die', hint: 'verweisen auf + Akkusativ' },
          { type: 'text', content: ' bessere Luft und auf mehr Platz ' },
          { type: 'blank', id: 'stadt-3', category: 'noun', answer: 'für die', hint: 'Platz für + Akkusativ' },
          { type: 'text', content: ' Bewohner. Wenn Cafes ihre Tische ' },
          { type: 'blank', id: 'stadt-4', category: 'location', answer: 'auf die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Straße stellen, entsteht ein anderes Gefühl ' },
          { type: 'blank', id: 'stadt-5', category: 'noun', answer: 'von der', hint: 'Gefühl von + Dativ' },
          { type: 'text', content: ' Stadt.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Kritiker warnen jedoch ' },
          { type: 'blank', id: 'stadt-6', category: 'verb', answer: 'vor den', hint: 'warnen vor + Dativ' },
          { type: 'text', content: ' Kosten. Lieferdienste sind abhängig ' },
          { type: 'blank', id: 'stadt-7', category: 'noun', answer: 'von den', hint: 'abhängig von + Dativ' },
          { type: 'text', content: ' Zufahrten, und ältere Menschen brauchen Zugang ' },
          { type: 'blank', id: 'stadt-8', category: 'noun', answer: 'zu den', hint: 'Zugang zu + Dativ' },
          { type: 'text', content: ' Ärzten im Zentrum. Darum sollte die Politik nicht nur Autos ' },
          { type: 'blank', id: 'stadt-9', category: 'location', answer: 'aus der', hint: 'woher? aus + Dativ' },
          { type: 'text', content: ' Innenstadt entfernen, sondern auch Geld ' },
          { type: 'blank', id: 'stadt-10', category: 'verb', answer: 'in den', hint: 'investieren in + Akkusativ' },
          { type: 'text', content: ' Nahverkehr investieren.' },
        ],
      },
    ],
  },
  {
    id: 'arbeitsplatz-im-wandel',
    title: 'Der Arbeitsplatz im Wandel',
    level: 'B2',
    kind: 'expository',
    description: 'Ein beruflicher Kontext mit Verantwortung, Abhängigkeit und räumlicher Organisation.',
    focus: ['verb', 'noun', 'location'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Im neuen Büro arbeitet das Team nicht mehr fest ' },
          { type: 'blank', id: 'arbeit-1', category: 'location', answer: 'an einem', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Platz. Wer konzentriert schreiben will, setzt sich ' },
          { type: 'blank', id: 'arbeit-2', category: 'location', answer: 'in den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' ruhigen Raum. Die Leitung achtet ' },
          { type: 'blank', id: 'arbeit-3', category: 'verb', answer: 'auf die', hint: 'achten auf + Akkusativ' },
          { type: 'text', content: ' Bedürfnisse der Mitarbeitenden und spricht regelmäßig ' },
          { type: 'blank', id: 'arbeit-4', category: 'verb', answer: 'mit dem', hint: 'sprechen mit + Dativ' },
          { type: 'text', content: ' Betriebsrat.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Trotzdem gibt es Kritik ' },
          { type: 'blank', id: 'arbeit-5', category: 'noun', answer: 'an der', hint: 'Kritik an + Dativ' },
          { type: 'text', content: ' neuen Ordnung. Manche haben Sorge ' },
          { type: 'blank', id: 'arbeit-6', category: 'noun', answer: 'um ihre', hint: 'Sorge um + Akkusativ' },
          { type: 'text', content: ' Privatsphäre, andere freuen sich ' },
          { type: 'blank', id: 'arbeit-7', category: 'verb', answer: 'über die', hint: 'sich freuen über + Akkusativ', explanation: 'sich freuen über = Reaktion auf etwas Vorhandenes; sich freuen auf = Erwartung.' },
          { type: 'text', content: ' flexiblen Zonen. Ein Bildschirm hängt ' },
          { type: 'blank', id: 'arbeit-8', category: 'location', answer: 'zwischen den', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Konferenzräumen und informiert ' },
          { type: 'blank', id: 'arbeit-9', category: 'verb', answer: 'über die', hint: 'informieren über + Akkusativ' },
          { type: 'text', content: ' freien Plätze. Der Erfolg hängt schließlich ' },
          { type: 'blank', id: 'arbeit-10', category: 'verb', answer: 'von der', hint: 'abhängen von + Dativ' },
          { type: 'text', content: ' gemeinsamen Nutzung ab.' },
        ],
      },
    ],
  },
  {
    id: 'nachhaltiger-konsum',
    title: 'Nachhaltiger Konsum im Alltag',
    level: 'B1-B2',
    kind: 'argumentative',
    description: 'Ein reflektierender Text über Konsum, Verantwortung und konkrete Alltagssituationen.',
    focus: ['noun', 'verb', 'location'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Wer nachhaltig leben möchte, denkt oft zuerst ' },
          { type: 'blank', id: 'konsum-1', category: 'verb', answer: 'an den', hint: 'denken an + Akkusativ' },
          { type: 'text', content: ' Einkauf. Obst liegt besser lose ' },
          { type: 'blank', id: 'konsum-2', category: 'location', answer: 'in der', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Tasche als in Plastik. Viele Menschen haben Interesse ' },
          { type: 'blank', id: 'konsum-3', category: 'noun', answer: 'an einer', hint: 'Interesse an + Dativ' },
          { type: 'text', content: ' fairen Produktion, aber sie achten im Laden stärker ' },
          { type: 'blank', id: 'konsum-4', category: 'verb', answer: 'auf den', hint: 'achten auf + Akkusativ' },
          { type: 'text', content: ' Preis.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Das Problem besteht nicht nur ' },
          { type: 'blank', id: 'konsum-5', category: 'verb', answer: 'aus den', hint: 'bestehen aus + Dativ' },
          { type: 'text', content: ' Verpackungen. Es geht auch ' },
          { type: 'blank', id: 'konsum-6', category: 'verb', answer: 'um die', hint: 'gehen um + Akkusativ' },
          { type: 'text', content: ' Gewohnheit, Dinge sofort zu ersetzen. Ein Reparaturcafe bietet Hilfe ' },
          { type: 'blank', id: 'konsum-7', category: 'noun', answer: 'bei der', hint: 'Hilfe bei + Dativ' },
          { type: 'text', content: ' Reparatur an und stellt Werkzeuge ' },
          { type: 'blank', id: 'konsum-8', category: 'location', answer: 'auf den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' großen Tisch. So entsteht Verantwortung ' },
          { type: 'blank', id: 'konsum-9', category: 'noun', answer: 'für die', hint: 'Verantwortung für + Akkusativ' },
          { type: 'text', content: ' eigenen Entscheidungen und Respekt ' },
          { type: 'blank', id: 'konsum-10', category: 'noun', answer: 'vor den', hint: 'Respekt vor + Dativ' },
          { type: 'text', content: ' Ressourcen.' },
        ],
      },
    ],
  },
  {
    id: 'museum-der-erinnerung',
    title: 'Im Museum der Erinnerung',
    level: 'B1',
    kind: 'narrative',
    description: 'Ein Museumsbesuch mit Ort, Richtung, Interesse und Erklärsituationen.',
    focus: ['location', 'noun', 'verb'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Die Klasse geht ' },
          { type: 'blank', id: 'museum-1', category: 'location', answer: 'in das', hint: 'wohin? + Akkusativ', acceptedAnswers: ['ins'] },
          { type: 'text', content: ' Stadtmuseum. Gleich am Eingang hängt ein altes Foto ' },
          { type: 'blank', id: 'museum-2', category: 'location', answer: 'über der', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Kasse. Die Schüler stellen sich ' },
          { type: 'blank', id: 'museum-3', category: 'location', answer: 'vor die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Vitrine und hören ' },
          { type: 'blank', id: 'museum-4', category: 'verb', answer: 'auf die', hint: 'hören auf + Akkusativ' },
          { type: 'text', content: ' Erklärung der Führerin.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Besonders groß ist ihr Interesse ' },
          { type: 'blank', id: 'museum-5', category: 'noun', answer: 'an den', hint: 'Interesse an + Dativ' },
          { type: 'text', content: ' Briefen aus der Nachkriegszeit. Eine Schülerin fragt ' },
          { type: 'blank', id: 'museum-6', category: 'verb', answer: 'nach dem', hint: 'fragen nach + Dativ' },
          { type: 'text', content: ' Alltag der Familien. Die Führerin zeigt ' },
          { type: 'blank', id: 'museum-7', category: 'location', answer: 'auf eine', hint: 'wohin?/Richtung: auf + Akkusativ' },
          { type: 'text', content: ' Karte und spricht ' },
          { type: 'blank', id: 'museum-8', category: 'verb', answer: 'über die', hint: 'sprechen über + Akkusativ', explanation: 'sprechen über = Thema; sprechen mit = Gesprächspartner.' },
          { type: 'text', content: ' zerstörten Straßen. Am Ende bleibt ein Gefühl ' },
          { type: 'blank', id: 'museum-9', category: 'noun', answer: 'für die', hint: 'Gefühl für + Akkusativ' },
          { type: 'text', content: ' Nähe der Geschichte und Dankbarkeit ' },
          { type: 'blank', id: 'museum-10', category: 'noun', answer: 'für den', hint: 'Dankbarkeit für + Akkusativ' },
          { type: 'text', content: ' Frieden.' },
        ],
      },
    ],
  },
  {
    id: 'pruefungsvorbereitung',
    title: 'Der Tag vor der Prüfung',
    level: 'B1-B2',
    kind: 'narrative',
    description: 'Eine realistische Lernszene mit Vorbereitung, Angst, Ordnung und konkreter Raumlogik.',
    focus: ['verb', 'noun', 'location'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Am Abend vor der Prüfung bereitet sich Samira ' },
          { type: 'blank', id: 'pruefung-1', category: 'verb', answer: 'auf den', hint: 'sich vorbereiten auf + Akkusativ' },
          { type: 'text', content: ' mündlichen Teil vor. Sie legt ihre Karteikarten ' },
          { type: 'blank', id: 'pruefung-2', category: 'location', answer: 'auf den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Tisch und schreibt schwierige Wörter ' },
          { type: 'blank', id: 'pruefung-3', category: 'location', answer: 'an die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Wand. Trotz ihrer Angst ' },
          { type: 'blank', id: 'pruefung-4', category: 'noun', answer: 'vor der', hint: 'Angst vor + Dativ' },
          { type: 'text', content: ' Prüfung glaubt sie ' },
          { type: 'blank', id: 'pruefung-5', category: 'verb', answer: 'an ihre', hint: 'glauben an + Akkusativ' },
          { type: 'text', content: ' Fortschritte.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Ihr Bruder fragt ' },
          { type: 'blank', id: 'pruefung-6', category: 'verb', answer: 'nach den', hint: 'fragen nach + Dativ' },
          { type: 'text', content: ' Themen und hilft ihr ' },
          { type: 'blank', id: 'pruefung-7', category: 'noun', answer: 'bei der', hint: 'Hilfe bei + Dativ' },
          { type: 'text', content: ' Wiederholung. Samira setzt sich nicht ' },
          { type: 'blank', id: 'pruefung-8', category: 'location', answer: 'vor den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Fernseher, sondern bleibt konzentriert ' },
          { type: 'blank', id: 'pruefung-9', category: 'location', answer: 'an dem', hint: 'wo? + Dativ', acceptedAnswers: ['am'] },
          { type: 'text', content: ' Schreibtisch. Kurz vor dem Schlafen freut sie sich sogar ' },
          { type: 'blank', id: 'pruefung-10', category: 'verb', answer: 'auf das', hint: 'sich freuen auf + Akkusativ', explanation: 'sich freuen auf = Erwartung; sich freuen über = Freude über etwas, das schon da ist.' },
          { type: 'text', content: ' Gespräch.' },
        ],
      },
    ],
  },
  {
    id: 'wohnen-in-der-stadt',
    title: 'Warum Wohnraum knapp wird',
    level: 'B2',
    kind: 'expository',
    description: 'Ein erklärender Text über Wohnungssuche, Stadtentwicklung und soziale Abhängigkeiten.',
    focus: ['noun', 'verb', 'location'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'In vielen Städten steigt die Nachfrage ' },
          { type: 'blank', id: 'wohnen-1', category: 'noun', answer: 'nach den', hint: 'Nachfrage nach + Dativ' },
          { type: 'text', content: ' kleinen Wohnungen. Studierende suchen ' },
          { type: 'blank', id: 'wohnen-2', category: 'verb', answer: 'nach einem', hint: 'suchen nach + Dativ' },
          { type: 'text', content: ' bezahlbaren Zimmer, Familien ziehen ' },
          { type: 'blank', id: 'wohnen-3', category: 'location', answer: 'in die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Randbezirke. Gleichzeitig investieren Unternehmen ' },
          { type: 'blank', id: 'wohnen-4', category: 'verb', answer: 'in die', hint: 'investieren in + Akkusativ' },
          { type: 'text', content: ' Modernisierung alter Häuser.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Der Streit ' },
          { type: 'blank', id: 'wohnen-5', category: 'noun', answer: 'um die', hint: 'Streit um + Akkusativ' },
          { type: 'text', content: ' Mieten wird emotional, weil viele Angst ' },
          { type: 'blank', id: 'wohnen-6', category: 'noun', answer: 'vor der', hint: 'Angst vor + Dativ' },
          { type: 'text', content: ' Verdrängung haben. Einige Politiker setzen Hoffnung ' },
          { type: 'blank', id: 'wohnen-7', category: 'noun', answer: 'auf den', hint: 'Hoffnung auf + Akkusativ' },
          { type: 'text', content: ' Neubau, andere verweisen ' },
          { type: 'blank', id: 'wohnen-8', category: 'verb', answer: 'auf die', hint: 'verweisen auf + Akkusativ' },
          { type: 'text', content: ' leerstehenden Büros. Entscheidend ist der Zugang ' },
          { type: 'blank', id: 'wohnen-9', category: 'noun', answer: 'zu den', hint: 'Zugang zu + Dativ' },
          { type: 'text', content: ' Orten, an denen Menschen arbeiten und lernen; ohne ihn bleibt die Stadt nur ' },
          { type: 'blank', id: 'wohnen-10', category: 'location', answer: 'auf dem', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Papier gerecht.' },
        ],
      },
    ],
  },
  {
    id: 'freizeit-in-den-bergen',
    title: 'Ein Wochenende in den Bergen',
    level: 'B1',
    kind: 'narrative',
    description: 'Eine erwachsene Freizeitszene mit Bewegung, Lage, Wetter und festen Wendungen.',
    focus: ['location', 'verb', 'noun'],
    paragraphs: [
      {
        id: 'p1',
        parts: [
          { type: 'text', content: 'Am Freitag fahren Nora und Cem ' },
          { type: 'blank', id: 'berge-1', category: 'location', answer: 'in die', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Berge. Ihre Pension liegt ' },
          { type: 'blank', id: 'berge-2', category: 'location', answer: 'zwischen den', hint: 'wo? + Dativ' },
          { type: 'text', content: ' Tannen und nicht weit ' },
          { type: 'blank', id: 'berge-3', category: 'location', answer: 'von dem', hint: 'von + Dativ', acceptedAnswers: ['vom'] },
          { type: 'text', content: ' See entfernt. Beim Frühstück sprechen sie ' },
          { type: 'blank', id: 'berge-4', category: 'verb', answer: 'über die', hint: 'sprechen über + Akkusativ' },
          { type: 'text', content: ' Route und entscheiden sich ' },
          { type: 'blank', id: 'berge-5', category: 'verb', answer: 'für den', hint: 'sich entscheiden für + Akkusativ' },
          { type: 'text', content: ' längeren Weg.' },
        ],
      },
      {
        id: 'p2',
        parts: [
          { type: 'text', content: 'Kurz vor dem Gipfel stellen sie die Rucksäcke ' },
          { type: 'blank', id: 'berge-6', category: 'location', answer: 'auf den', hint: 'wohin? + Akkusativ' },
          { type: 'text', content: ' Boden und schauen ' },
          { type: 'blank', id: 'berge-7', category: 'location', answer: 'in das', hint: 'Richtung: in + Akkusativ', acceptedAnswers: ['ins'] },
          { type: 'text', content: ' Tal. Cem hat Respekt ' },
          { type: 'blank', id: 'berge-8', category: 'noun', answer: 'vor dem', hint: 'Respekt vor + Dativ' },
          { type: 'text', content: ' steilen Abstieg, aber Nora erinnert ihn ' },
          { type: 'blank', id: 'berge-9', category: 'verb', answer: 'an die', hint: 'erinnern an + Akkusativ' },
          { type: 'text', content: ' gute Ausrüstung. Am Ende sind beide stolz ' },
          { type: 'blank', id: 'berge-10', category: 'noun', answer: 'auf ihre', hint: 'stolz auf + Akkusativ' },
          { type: 'text', content: ' ruhige Entscheidung.' },
        ],
      },
    ],
  },
]

export const getPrepositionStoryById = (id: string) =>
  prepositionStories.find((story) => story.id === id)

export const getPrepositionBlanks = (story: PrepositionStory): PrepositionBlankPart[] =>
  story.paragraphs.flatMap((paragraph) =>
    paragraph.parts.filter((part): part is PrepositionBlankPart => part.type === 'blank')
  )

export const countPrepositionBlanksByCategory = (story: PrepositionStory) => {
  const counts: Record<PrepositionCategory, number> = {
    verb: 0,
    location: 0,
    noun: 0,
  }

  getPrepositionBlanks(story).forEach((blank) => {
    counts[blank.category] += 1
  })

  return counts
}
